MyCourse/Models/Services/Application/Lessons/AdoNetLessonService.cs
using MyCourse.Models.InputModels;
using MyCourse.Models.Services.Application.Courses;
using MyCourse.Models.Services.Infrastructure;
using MyCourse.Models.ViewModel.Lessons;
using System.Data;

namespace MyCourse.Models.Services.Application.Lessons
{
    public class AdoNetLessonService : ILessonService
    {
        private readonly IDatabaseAccessor db;
        private readonly ILogger<AdoNetCourseService> log;

        public AdoNetLessonService(IDatabaseAccessor db, ILogger<AdoNetCourseService> log)
        {
            this.db = db;
            this.log = log;
        }

        public async Task<LessonDetailViewModel> CreateLessonAsync(LessonCreateInputModel inputModel)
        {
            string title = inputModel.Title;
            int courseId = inputModel.CourseId;

            FormattableString cmd = @$"INSERT INTO Lessons (CourseId, Title) VALUES ({courseId}, '{title}');
                                    SELECT TOP 1 * FROM Lessons ORDER BY Id DESC";

            #region Query to try
            //TODO: Provare ad usare questa query SELECT * FROM Lessons WHERE Id = (SELECT MAX(Id) FROM Lessons);
            #endregion

            int lessonID = await db.QueryScalarAsync<int>(cmd);

            LessonDetailViewModel lesson = await GetLessonAsync(lessonID);

            return lesson;
        }

        public async Task DeleteLessonAsync(LessonDeleteInputModel inputModel)
        {
            int affected = await db.CommandAsync($"DELETE FROM Lessons WHERE Id = {inputModel.Id}");

        }

        public async Task<LessonDetailViewModel> EditLessonAsync(LessonEditInputModel editModel)
        {
            FormattableString cmd = @$"UPDATE Lessons SET Title = '{editModel.Title}', Description = '{editModel.Description}',
                                        Duration = '{editModel.Duration}' WHERE Id = {editModel.Id}";

            int affectedRows = await db.CommandAsync(cmd);

            LessonDetailViewModel editedLesson = await GetLessonAsync(editModel.Id);

            return editedLesson;
        }

        public async Task<LessonDetailViewModel> GetLessonAsync(int id)
        {
            FormattableString query = $"SELECT * FROM Lessons WHERE Id = {id}";

            DataSet dataSet = await db.QueryAsync(query);
            DataTable dataTable = dataSet.Tables[0];

            //TODO: Add exception for lesson not found!
            if (dataTable.Rows.Count != 1)
            {
                throw new Exception();
            }

            DataRow lessonRow = dataTable.Rows[0];

            LessonDetailViewModel viewModel = LessonDetailViewModel.FromDataRow(lessonRow);

            return viewModel;
        }

        public async Task<LessonEditInputModel> GetLessonForEditingAsync(int id)
        {
            FormattableString query = $"SELECT * FROM Lessons WHERE Id = {id}";

            DataSet dataSet = await db.QueryAsync(query);
            DataTable dataTable = dataSet.Tables[0];

            if (dataTable.Rows.Count != 1) { throw new Exception(); }

            DataRow lessonRow = dataTable.Rows[0];

            LessonEditInputModel editModel = LessonEditInputModel.FromDataRow(lessonRow);

            return editModel;
        }
    }

}

MyCourse/Models/Services/Application/Lessons/ICachedLessonService.cs
namespace MyCourse.Models.Services.Application.Lessons
{
    public interface ICachedLessonService : ILessonService
    {
    }
}

MyCourse/Models/Services/Application/Lessons/ILessonService.cs
using MyCourse.Models.InputModels;
using MyCourse.Models.ViewModel.Lessons;

namespace MyCourse.Models.Services.Application.Lessons
{
    public interface ILessonService
    {
        Task<LessonDetailViewModel> CreateLessonAsync(LessonCreateInputModel inputModel);
        Task DeleteLessonAsync(LessonDeleteInputModel inputModel);
        Task<LessonDetailViewModel> EditLessonAsync(LessonEditInputModel editModel);
        Task<LessonDetailViewModel> GetLessonAsync(int lessonId);
        Task<LessonEditInputModel> GetLessonForEditingAsync(int id);
    }
}

MyCourse/Models/ViewModel/Lessons/LessonDetailViewModel.cs
using System.Data;

namespace MyCourse.Models.ViewModel.Lessons
{
    public class LessonDetailViewModel
    {
        public int Id { get; set; }
        public int CourseId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Duration { get; set; }

        internal static LessonDetailViewModel FromDataRow(DataRow lessonRow)
        {
            var lessonViewModel = new LessonDetailViewModel
            {
                Id = Convert.ToInt32(lessonRow["Id"]),
                CourseId = Convert.ToInt32(lessonRow["CourseId"]),
                Title = Convert.ToString(lessonRow["Title"]),
                Description = Convert.ToString(lessonRow["Description"]),
                Duration = Convert.ToString(lessonRow["Duration"])
            };

            return lessonViewModel;
        }
    }
}

MyCourse/Models/ViewModel/Lessons/LessonViewModel.cs
using System.Data;

namespace MyCourse.Models.ViewModel.Lessons
{
    public class LessonViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Duration { get; set; }

        public static LessonViewModel FromDataRow(DataRow row)
        {
            LessonViewModel viewmodel = new LessonViewModel
            {
                Id = (int) row["Id"],
                Name = (string) row["Title"],
                Duration = Convert.ToString(row["Duration"])
            };

            return viewmodel;
        }
    }
}

MyCourse/Controllers/Lessons/LessonsController.cs
using Microsoft.AspNetCore.Mvc;
using MyCourse.Controllers.Courses;
using MyCourse.Models.Exceptions;
using MyCourse.Models.InputModels;
using MyCourse.Models.Services.Application.Lessons;
using MyCourse.Models.ViewModel.Lessons;
using System.Threading.Tasks;

namespace MyCourse.Controllers.Lessons
{
    public class LessonsController : Controller
    {
        private readonly ILessonService lessonService;

        public LessonsController(ILessonService lessonService)
        {
            this.lessonService = lessonService;
        }

        public async Task<IActionResult> Detail(int id)
        {
            ViewData["Title"] = $"Lezione {id}";
            LessonDetailViewModel lesson = await lessonService.GetLessonAsync(id);
            return View(lesson);
        }

        public IActionResult Create(int id)
        {
            ViewData["Title"] = "Nuova lezione";
            LessonCreateInputModel inputModel = new LessonCreateInputModel();
            inputModel.CourseId = id;
            return View(inputModel);
        }

        [HttpPost]
        public async Task<IActionResult> Create(LessonCreateInputModel inputModel)
        {
            if (ModelState.IsValid)
            {
                LessonDetailViewModel lesson = await lessonService.CreateLessonAsync(inputModel);
                TempData["ConfirmationMessage"] = "Ok! La lezione è stata creata, aggiungi anche gli altri dati";
                return RedirectToAction(nameof(Edit), new { id = inputModel.Id});
            }

            ViewData["Title"] = "Nuova Lezioni";
            return View(inputModel);
        }

        public async Task<IActionResult> Edit(int id)
        {
            ViewData["Title"] = "Modifica Lezione";
            LessonEditInputModel editModel = await lessonService.GetLessonForEditingAsync(id);
            return View(editModel);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(LessonEditInputModel editModel)
        {
            if (ModelState.IsValid)
            {
                LessonDetailViewModel editedLesson = await lessonService.EditLessonAsync(editModel);
                TempData["ConfirmationMessage"] = "Ok, i dati della lezione sono stati inseriti correttamente! Ecco qua:";
                return RedirectToAction(nameof(Detail), new { id = editedLesson.Id });
            }

            ViewData["Title"] = "Modifica Lezione";
            return View(editModel);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(LessonDeleteInputModel inputModel)
        {
            await lessonService.DeleteLessonAsync(inputModel);
            TempData["ConfirmationMessage"] = "La lezione è stata eliminata";
            return RedirectToAction(nameof(CoursesController.Detail), "Courses", new { id = inputModel.CourseId });
        }
    }
}

MyCourse/Views/Lessons/Create.cshtml
@model LessonCreateInputModel

<h2>Crea Nuova Lezione</h2>
<div class="row">
    <div class="col-md-12">
        <div asp-validation-summary="All"></div>
    </div>
</div>
<form method="post">
    <section class="row">
        <div class="col-md-8">
            <input type="text" asp-for="Title" placeholder="Inserisci un titolo..." class="form-control form-control-lg" />
            <span asp-validation-for="Title"></span>
            <input type="hidden" asp-for="CourseId"/>
        </div>
        <div class="col-md-4">
            <button type="submit" class="btn btn-outline-primary btn-lg btn-block" asp-action="Create" asp-controller="Lessons">
                <i class="bi bi-rocket-takeoff me-2"></i>Crea Lezione
            </button>
        </div>
    </section>
</form>

@section Scripts
{
    <partial name="_Validation"></partial>
}

MyCourse/Views/Lessons/Detail.cshtml
@using MyCourse.Models.ViewModel.Lessons
@model LessonDetailViewModel

<section>
    <div class="row">
        <div class="col-md-9 d-flex align-items-center gap-3">
            <h1>@Model.Title</h1>
        </div>
    </div>
    <div class="row mt-3">
        <div class="col-md-9">
            <h4>Duration: @Model.Duration</h4>
            <p html-sanitize>@Model.Description</p>
        </div>
    </div>
    <div>
        <a asp-controller="Courses" asp-action="Detail" asp-route-id="@Model.CourseId"><i class="fas fa-arrow-left"></i> Torna al corso</a>
    </div>
</section>

MyCourse/Views/Lessons/Edit.cshtml
@model LessonEditInputModel

<form method="post">
    <div class="row my-3">
        <div class="col-md-9">
            <h1>@ViewData["Title"]</h1>
            @* <input type="hidden" asp-for="RowVersion" /> *@
            <input type="hidden" asp-for="CourseId" />
        </div>
        <div class="col-md-3">
            <button type="submit" class="btn btn-primary btn-lg">Salva</button>
            <button type="button" class="btn btn-danger btn-lg" data-bs-toggle="modal" data-bs-target="#delete-modal">
                <i class="bi bi-trash3-fill"></i>
            </button>
        </div>



        <div class="row">
            <div class="col-12" asp-validation-summary="All"></div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-9">
            <label asp-for="Title"></label>
            <div class="input-group">
                <input type="text" asp-for="Title" class="form-control" />
                <span asp-validation-for="Title"></span>
            </div>
            <label asp-for="Description"></label>
            <div class="input-group">
                <textarea asp-for="Description" class="form-control" rows="15" data-summernote></textarea>
                <span asp-validation-for="Description"></span>
            </div>
        </div>
        <div class="col-md-3">
            <label asp-for="Duration"></label>
            <div class="input-group">
                <input type="text" asp-for="Duration" class="form-control" />
                <span asp-validation-for="Duration"></span>
            </div>
        </div>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="delete-modal" tabindex="-1" aria-labelledby="delete-modal" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="delete-modal">Conferma Eliminazione</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    Stai per eliminare la lezione e tutti i suoi dati andranno persi. Sei sicuro di voler procedere?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="submit" asp-action="Delete" asp-route-id="@Model.Id" class="btn btn-danger">Conferma</button>
                </div>
            </div>
        </div>
    </div>
</form>